# Базовый образ
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 6443

# Сборка приложения
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Warehouse.API.csproj", "."]
RUN dotnet restore "Warehouse.API.csproj"

# Копируем все файлы проекта, включая wwwroot
COPY . .
RUN dotnet build "Warehouse.API.csproj" -c Release -o /app/build

# Публикация
FROM build AS publish
RUN dotnet publish "Warehouse.API.csproj" -c Release -o /app/publish

# Финальный образ
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
COPY ["app.db", "/app/"]
ENTRYPOINT ["dotnet", "Warehouse.API.dll"]